### ISSUE TITLE
`Exception happened during processing of request from ('127.0.0.1', 51937)`

### ISSUE THREAD

**Issue by arokem** [nvdv/vprof#12]
Thanks for making this useful project available! 

I pip installed it (Mac OS 10.11.3, Anaconda Python 3.5.1), and then tried running it. I get the messages saying that it's running the various profiling functionalities (depending on the flags), and then a blank browser tab opens pointing to localhost:8000. The message in the title then appears in the terminal. 

Any ideas? Thanks again

**Comment by nirum** [comment]
I get the same error. Also, in the browser console, there is a syntax error in `vprof_min.js`:

![screen shot 2016-02-10 at 2 40 32 pm](https://cloud.githubusercontent.com/assets/904854/12964302/4504cf4e-d004-11e5-8b62-b882389696c3.png)

**Comment by jorisvandenbossche** [comment]
I get a similar error on Windows (although I first had to change the `subprocess.call(['open', 'http://%s:%s' % (host, port)])` line as `open` is not a command on Windows):

```
Exception happened during processing of request from ('127.0.0.1', 54772)
```

**Comment by nvdv** [comment]
Thanks for reporting!

I have created a separate issue for Windows compatibility.

I've just added debug mode to ```vprof```.
Did you install ```vprof``` from sources or from PyPI?

If you installed ```vprof``` from sources, update your copy of repo, execute ```make install``` and add ```--debug``` to command you used to run ```vprof``` to see error messages.

If you installed ```vprof``` from PyPi, let me know and I will update package on PyPI.

**Comment by jorisvandenbossche** [comment]
I installed from PyPI, but I now installed from source to make it a bit easier to test. This is the output I get:

```
[py35] C:\Users\vdbosscj\Scipy>vprof c test_timeseries_perf_regression.py --po
rt 9000 --debug
Running RuntimeProfile...
0.17.1
1.5.0
Starting HTTP server...
Serving HTTP on 127.0.0.1 port 9000 ...
127.0.0.1 - - [11/Feb/2016 13:14:36] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2016 13:14:36] "GET /vprof.css HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61317)
Traceback (most recent call last):
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 628, in process_request
_thread
    self.finish_request(request, client_address)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 37, in __init
__
    self, *args, **kwargs)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 415, in handle
    self.handle_one_request()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 403, in handle_one_reque
st
    method()
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 53, in do_GET

    output = res_file.read()
  File "C:\Anaconda\envs\py35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 33020: ch
aracter maps to <undefined>
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61316)
Traceback (most recent call last):
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 628, in process_request
_thread
    self.finish_request(request, client_address)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 37, in __init
__
    self, *args, **kwargs)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 415, in handle
    self.handle_one_request()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 403, in handle_one_reque
st
    method()
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 52, in do_GET

    with open(res_filename) as res_file:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\vdbosscj\\sc
ipy\\vprof\\vprof/frontend/favicon.ico'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 61318)
Traceback (most recent call last):
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 628, in process_request
_thread
    self.finish_request(request, client_address)
----------------------------------------
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
Exception happened during processing of request from ('127.0.0.1', 61319)
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 37, in __init
__
    self, *args, **kwargs)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 415, in handle
    self.handle_one_request()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 403, in handle_one_reque
st
    method()
Traceback (most recent call last):
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 52, in do_GET

    with open(res_filename) as res_file:
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 628, in process_request
_thread
    self.finish_request(request, client_address)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\vdbosscj\\sc
ipy\\vprof\\vprof/frontend/favicon.ico'
----------------------------------------
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 37, in __init
__
    self, *args, **kwargs)
  File "C:\Anaconda\envs\py35\lib\socketserver.py", line 684, in __init__
    self.handle()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 415, in handle
    self.handle_one_request()
  File "C:\Anaconda\envs\py35\lib\http\server.py", line 403, in handle_one_reque
st
    method()
  File "c:\users\vdbosscj\scipy\vprof\vprof\stats_server.py", line 52, in do_GET

    with open(res_filename) as res_file:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\vdbosscj\\sc
ipy\\vprof\\vprof/frontend/favicon.ico'
----------------------------------------
```

**Comment by jorisvandenbossche** [comment]
It seems a python 3 issue, as it does work with python 2.7

**Comment by bilderbuchi** [comment]
` No such file or directory: 'c:\\users\\vdbosscj\\scipy\\vprof\\vprof/frontend/favicon.ico'`
These paths look wonky, when constructing [here](https://github.com/nvdv/vprof/blob/d816b48d66439b7f4a32d44cd89ba6ba579e5ba4/vprof/stats_server.py#L42), it would probably be better to use `os.sep` (or optimally: [os.path.join](https://docs.python.org/3.5/library/os.path.html#os.path.join) to construct the paths, this way you avoid mixing slash and backslash.

**Comment by nvdv** [comment]
Can anyone confirm that this one is fixed now, since I am not a Windows user?

**Comment by arokem** [comment]
Yep. Works for me (but I'm on a Mac, not Windows).

**Comment by arokem** [comment]
BTW - the message still appears in my terminal. It's just that it doesn't seem to matter now :-)

**Comment by nvdv** [comment]
What kind of error message do you see in your terminal? This one #10 ?

**Comment by arokem** [comment]
No - the same as in the title of this issue report.

**Comment by jorisvandenbossche** [comment]
@arokem Did you try it with the `--debug` option?

**Comment by nvdv** [comment]
I've just updated PyPI version. Does this message still appear in logs?

**Comment by nirum** [comment]
Just tried it with the version on PyPI, it works for me, no error messages.

(Mac OS X, Python 3)

**Comment by soupault** [comment]
I confirm that this message is still being shown:
```
[user@machine restoration]$ vprof c plot_inpaint.py 
Running RuntimeProfile...
Starting HTTP server...
Created new window in existing browser session.
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 47256)
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 47260)
----------------------------------------
^CStopping...
```
Archlinux x64, Python 3.5 (btw, is there a way to force `vprof` to use another binary?), pip installed vprof.

**Comment by nvdv** [comment]
@soupault Can you run ```vprof``` with ```--debug``` flag: ```vprof c plot_inpaint.py --debug```?

**Comment by soupault** [comment]
@nvdv ,
```
[user@machine restoration]$ vprof c plot_inpaint.py --debug
Running RuntimeProfile...
Starting HTTP server...
Created new window in existing browser session.
127.0.0.1 - - [23/Feb/2016 12:00:47] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [23/Feb/2016 12:00:47] "GET /vprof.css HTTP/1.1" 200 -
127.0.0.1 - - [23/Feb/2016 12:00:47] "GET /vprof_min.js HTTP/1.1" 200 -
127.0.0.1 - - [23/Feb/2016 12:00:48] "GET /profile HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55868)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 32, in __init__
    self, *args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 403, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 59, in do_GET
    content, content_type = handler()
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 51, in handle_other
    with io.open(res_filename, 'rb') as res_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/vprof/frontend/favicon.ico'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 55872)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 628, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 32, in __init__
    self, *args, **kwargs)
  File "/usr/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 403, in handle_one_request
    method()
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 59, in do_GET
    content, content_type = handler()
  File "/usr/lib/python3.5/site-packages/vprof/stats_server.py", line 51, in handle_other
    with io.open(res_filename, 'rb') as res_file:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/vprof/frontend/favicon.ico'
----------------------------------------
^CStopping...
```

**Comment by nvdv** [comment]
Thanks!
Now it's duplicate of #10.

**Comment by soupault** [comment]
@nvdv Yup, seems like. In any case, the utility works fine and the warning doesn't really affect the results.

**Comment by veken1199** [comment]
Had similar issue in python 3.5.3c, Updated python to 3.7 solved the problem

**Comment by Gautamankul2795** [comment]
how can fixed it please comment fast

**Comment by alfaser123** [comment]
> 
> 
> how can fixed it please comment fast

I got that problem when I installed two versions of Odoo in windows using same database.   Odoo create Odoo service for each versión. I get that error using one version or another.  I just stop one service version and keep active the one I want to use and problem resolved.

**Comment by yashgaikwad002** [comment]
there is already a log file in my directory
